language: cpp
arch: amd64
os: linux 
dist: bionic

before_install:
    - sudo apt-get update
    - sudo apt-get install -y python build-essential zlib1g-dev xz-utils clang
    - sudo chmod +x ./install-deps.sh && sudo ./install-deps.sh

compiler:
  - clang

# Build steps
script: 
  - cd ${TRAVIS_BUILD_DIR}
  - cmake . 
  - make
  - ctest


after_success:
- ls
- echo "done"


