language: cpp
arch: amd64
os: linux 
dist: bionic

before_install:
    - sudo apt-get update
    - sudo apt-get install -y python libcurl4-openssl-dev build-essential zlib1g-dev xz-utils clang cmake
    - wget https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz 
    - tar xfz boost_1_72_0.tar.gz     && rm boost_1_72_0.tar.gz     && cd boost_1_72_0     && sudo ./bootstrap.sh     && sudo ./b2 --without-python --prefix=/usr -j 4 link=static runtime-link=static install     && cd .. && rm -rf boost_1_72_0/ && sudo ldconfig

compiler:
  - clang

# Build steps
script: 
  - cd ${TRAVIS_BUILD_DIR}
  - cmake . 
  - make
  - ./tests/VarIntTest


after_success:
- ls
- echo "done"


