language: cpp
arch: amd64
os: linux 
dist: bionic

services:
    - docker

before_install:
    - sudo docker pull cub949/mcidle-builder

# Build steps
script: 
    - sudo docker build -t ci -f DockerfileCI .

after_success:
- ls
- echo "done"


